"""xArm 6 wrapper: load, home pose, joint state, position control.

Uses the flat xArm 6 URDF that ships with `pybullet_data` — no vendoring,
no extra deps. This is the UFactory model, autogenerated from their
official xacro (see bulletphysics/bullet3, path: pybullet_data/xarm/).

Scope of this commit: get the arm on screen, holding a home pose, and
respond to `set_joint_positions()`. No IK yet — that's the next commit,
where a debug marker feeds a target pose to a `solve_ik()` method here.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Sequence

import numpy as np
import pybullet as p
import pybullet_data

from sim.world import World

# ---------------------------------------------------------------- constants

# xArm 6 has 6 revolute joints. The bundled URDF's link6 is the last
# link and doubles as the tool frame (there is no separate `link_eef`).
XARM6_URDF_RELPATH = "xarm/xarm6_robot.urdf"
XARM6_NUM_JOINTS = 6

# Battle-tested "ready to reach forward" home pose for xArm 6 in PyBullet:
# base facing +x, shoulder tilted, elbow bent, wrist pointed down-ish.
# Values borrowed from the Google Research xarm_sim_robot reference
# (deg2rad([0, -20, -80, 0, 100, -30])).
DEFAULT_HOME_POSE_RAD: tuple[float, ...] = (
    0.0, -0.349, -1.396, 0.0, 1.745, -0.524,
)


# ------------------------------------------------------------------ config

@dataclass
class ArmConfig:
    """All tunable knobs for the arm. Base pose is separate because the
    AGV mount (commit 6) will override it at construction time."""

    base_position: tuple[float, float, float] = (0.0, 0.0, 0.0)
    base_orientation_rpy: tuple[float, float, float] = (0.0, 0.0, 0.0)

    home_pose_rad: tuple[float, ...] = DEFAULT_HOME_POSE_RAD

    # POSITION_CONTROL parameters. Used only when kinematic_control=False.
    max_force: float = 500.0
    position_gain: float = 1.0
    velocity_gain: float = 2.0

    # Kinematic control mode. When True (default), control_step teleports
    # joints toward the commanded target at bounded velocity via
    # resetJointState — no PD tuning, guaranteed convergence, no fight
    # with gravity. Consistent with the kinematic AGV and kinematic
    # gripper-mount pattern already used elsewhere in the sim. The
    # thesis's research question is about D(t) offloading decisions,
    # not arm joint dynamics, so this is the right level of abstraction.
    #
    # Trade-off: the arm can push through dynamic objects (kinematic
    # bodies ignore contact response). Grasping still works because
    # fingers use POSITION_CONTROL (dynamic) and object hold is enforced
    # via a fixed constraint set by GraspCycle during CLOSE.
    kinematic_control: bool = True
    # Max joint velocity when advancing kinematically (rad/s). At 30 Hz
    # control this means ~4° per tick, so a 60° motion takes ~0.5 s.
    max_joint_velocity_rps: float = 2.0
    # Force used to lock joint velocity to zero between kinematic
    # advances. Needs to be higher than any gravity torque the arm
    # experiences — 500 Nm is well above xArm 6's rated joint torques
    # (~50 Nm on strongest joints).
    kinematic_lock_force: float = 500.0

    # If True, use resetJointState (teleport) on reset() to snap to home
    # before the sim starts stepping. If False, home is reached under
    # position control after step-in.
    snap_to_home: bool = True

    # Whether to attach a parallel-jaw gripper to the arm's ee link.
    # When True, Arm.reset() also creates a Gripper (see sim/gripper.py).
    with_gripper: bool = True

    def __post_init__(self) -> None:
        if len(self.home_pose_rad) != XARM6_NUM_JOINTS:
            raise ValueError(
                f"home_pose_rad must have {XARM6_NUM_JOINTS} entries, "
                f"got {len(self.home_pose_rad)}"
            )


# --------------------------------------------------------------------- arm

class Arm:
    """PyBullet xArm 6 wrapper attached to a World.

    Owns:
        - the loaded URDF body id
        - the mapping from arm joints to PyBullet joint indices
        - the current target joint positions (applied every control tick)

    Does not own:
        - the physics loop (that's World)
        - IK solving (that's the next commit)
        - the base pose after construction (the AGV mount will move it)
    """

    def __init__(self, world: World, cfg: ArmConfig | None = None) -> None:
        self.world = world
        self.cfg = cfg or ArmConfig()

        self.body_id: int = -1
        self.joint_indices: list[int] = []  # PyBullet joint indices for the 6 revolute joints
        self.joint_names: list[str] = []
        self.joint_limits_lower: np.ndarray = np.zeros(XARM6_NUM_JOINTS)
        self.joint_limits_upper: np.ndarray = np.zeros(XARM6_NUM_JOINTS)
        self.ee_link_index: int = -1  # link6 — tool frame

        # Current position-control target. Updated by set_joint_positions()
        # and re-applied every control_step().
        self._target_q: np.ndarray = np.array(self.cfg.home_pose_rad,
                                              dtype=np.float64)

        # Populated by reset() if cfg.with_gripper=True.
        self.gripper = None  # type: ignore[assignment]

    # ------------------------------------------------------------- lifecycle

    def reset(self) -> None:
        """Load the URDF, discover joint indices, and go to home pose."""
        if self.world.client_id < 0:
            raise RuntimeError("World.reset() must be called before Arm.reset()")

        urdf_path = os.path.join(pybullet_data.getDataPath(),
                                 XARM6_URDF_RELPATH)
        if not os.path.isfile(urdf_path):
            raise FileNotFoundError(
                f"xArm 6 URDF not found at {urdf_path}. "
                "Is pybullet_data installed? (pip install pybullet)"
            )

        base_orn = p.getQuaternionFromEuler(self.cfg.base_orientation_rpy)
        self.body_id = p.loadURDF(
            urdf_path,
            basePosition=self.cfg.base_position,
            baseOrientation=base_orn,
            useFixedBase=True,
            physicsClientId=self.world.client_id,
        )

        self._discover_joints()

        # Reset current target to home before we snap or command.
        self._target_q = np.array(self.cfg.home_pose_rad, dtype=np.float64)

        if self.cfg.snap_to_home:
            for idx, q in zip(self.joint_indices, self._target_q):
                p.resetJointState(self.body_id, idx, q,
                                  physicsClientId=self.world.client_id)

        # Whether we snapped or not, hand off control to the appropriate
        # controller. In POSITION_CONTROL mode we send the home target
        # so the arm holds against gravity. In kinematic mode we set the
        # motors to a VELOCITY_CONTROL lock (target vel=0 with strong
        # force). Combined with resetJointState each control tick, this
        # is what keeps joints at commanded positions: physics tries to
        # move them (gravity), motor brakes them back.
        #
        # Setting force=0 (as an earlier version did) frees the motors
        # entirely — bounded joints hit their limits, but unbounded ones
        # (wrist rotations, joints 4 & 6) spin under gravity. Verified
        # by scripts/debug_arm_hold.py: with force=0, joint6 drifted
        # to -211° in 7 seconds; joints 1-3,5 with tighter limits held
        # correctly. Strong VELOCITY_CONTROL fixes it uniformly.
        if self.cfg.kinematic_control:
            self._enable_kinematic_lock()
        else:
            self._apply_target()

        # Spawn the gripper AFTER the arm is homed, so the gripper loads
        # at the correct ee pose from the start.
        if self.cfg.with_gripper:
            from sim.gripper import Gripper, GripperConfig  # local import to avoid cycle
            self.gripper = Gripper(self.world, self, GripperConfig())
            self.gripper.reset()

    def _enable_kinematic_lock(self) -> None:
        """Configure joint motors as a velocity-zero brake. Each motor
        applies torque up to `kinematic_lock_force` to keep the joint's
        velocity at zero — this cancels out gravity-induced motion
        between resetJointState calls in _kinematic_advance."""
        p.setJointMotorControlArray(
            bodyUniqueId=self.body_id,
            jointIndices=self.joint_indices,
            controlMode=p.VELOCITY_CONTROL,
            targetVelocities=[0.0] * XARM6_NUM_JOINTS,
            forces=[self.cfg.kinematic_lock_force] * XARM6_NUM_JOINTS,
            physicsClientId=self.world.client_id,
        )

    def _discover_joints(self) -> None:
        """Walk the loaded body's joints and record the 6 revolute ones.

        We don't hardcode joint indices because the URDF has a fixed
        world_joint at index 0 (see the bundled URDF header) — the
        actual revolute joints are indices 1..6. But rather than assume
        that, we scan and take all JOINT_REVOLUTE joints in URDF order.
        """
        n = p.getNumJoints(self.body_id, physicsClientId=self.world.client_id)

        self.joint_indices = []
        self.joint_names = []
        lowers: list[float] = []
        uppers: list[float] = []

        for i in range(n):
            info = p.getJointInfo(self.body_id, i,
                                  physicsClientId=self.world.client_id)
            joint_type = info[2]
            if joint_type != p.JOINT_REVOLUTE:
                continue
            self.joint_indices.append(i)
            self.joint_names.append(info[1].decode("utf-8"))
            lowers.append(info[8])   # jointLowerLimit
            uppers.append(info[9])   # jointUpperLimit

        if len(self.joint_indices) != XARM6_NUM_JOINTS:
            raise RuntimeError(
                f"Expected {XARM6_NUM_JOINTS} revolute joints on the "
                f"xArm 6, found {len(self.joint_indices)}: {self.joint_names}"
            )

        self.joint_limits_lower = np.array(lowers, dtype=np.float64)
        self.joint_limits_upper = np.array(uppers, dtype=np.float64)

        # Tool frame = last link = link6. Its index equals the index of
        # joint6 in the URDF (PyBullet numbers links by their parent joint).
        self.ee_link_index = self.joint_indices[-1]

    # --------------------------------------------------------------- control

    def set_joint_positions(self, q: Sequence[float]) -> None:
        """Set the joint target. Takes effect on the next control_step().
        Values are clipped to joint limits.

        In POSITION_CONTROL mode, immediately pushes the target to the
        controller so callers who don't drive a control loop still see
        motion. In kinematic mode, we skip the immediate apply — the
        next kinematic_advance() will handle it."""
        q_arr = np.asarray(q, dtype=np.float64)
        if q_arr.shape != (XARM6_NUM_JOINTS,):
            raise ValueError(
                f"q must have {XARM6_NUM_JOINTS} entries, got shape {q_arr.shape}"
            )
        self._target_q = np.clip(q_arr,
                                 self.joint_limits_lower,
                                 self.joint_limits_upper)
        if not self.cfg.kinematic_control:
            self._apply_target()

    def go_home(self) -> None:
        """Command the home pose as the current target."""
        self.set_joint_positions(self.cfg.home_pose_rad)

    def control_step(self, sim_time_s: float) -> None:
        """Callback for World.register_callback(). Advances joints toward
        the current target, either kinematically (default) or via
        POSITION_CONTROL depending on cfg.kinematic_control."""
        if self.cfg.kinematic_control:
            self._kinematic_advance()
        else:
            self._apply_target()

    def _kinematic_advance(self) -> None:
        """Move each joint toward its target by at most max_step per tick,
        via resetJointState with zero velocity. Guarantees convergence,
        no gain tuning, no gravity to fight."""
        # Estimate control tick rate from the world. Callback runs at
        # whatever rate the caller registered; we approximate 30 Hz here
        # for the step-size calculation. Slightly conservative is fine.
        max_step = self.cfg.max_joint_velocity_rps / 30.0

        q_actual = self.get_joint_positions()
        q_delta = self._target_q - q_actual
        q_step = np.clip(q_delta, -max_step, max_step)
        q_new = q_actual + q_step

        for idx, val in zip(self.joint_indices, q_new):
            p.resetJointState(
                self.body_id, idx,
                targetValue=float(val),
                targetVelocity=0.0,
                physicsClientId=self.world.client_id,
            )

    def _apply_target(self) -> None:
        p.setJointMotorControlArray(
            bodyUniqueId=self.body_id,
            jointIndices=self.joint_indices,
            controlMode=p.POSITION_CONTROL,
            targetPositions=self._target_q.tolist(),
            forces=[self.cfg.max_force] * XARM6_NUM_JOINTS,
            positionGains=[self.cfg.position_gain] * XARM6_NUM_JOINTS,
            velocityGains=[self.cfg.velocity_gain] * XARM6_NUM_JOINTS,
            physicsClientId=self.world.client_id,
        )

    # ---------------------------------------------------------- introspection

    def get_joint_positions(self) -> np.ndarray:
        """Actual current joint angles (not the target)."""
        states = p.getJointStates(self.body_id, self.joint_indices,
                                  physicsClientId=self.world.client_id)
        return np.array([s[0] for s in states], dtype=np.float64)

    def get_target_positions(self) -> np.ndarray:
        return self._target_q.copy()

    def get_ee_pose(self) -> tuple[np.ndarray, np.ndarray]:
        """World-frame (position, quaternion) of the tool link."""
        state = p.getLinkState(self.body_id, self.ee_link_index,
                               computeForwardKinematics=True,
                               physicsClientId=self.world.client_id)
        pos = np.array(state[4], dtype=np.float64)   # linkWorldPosition
        orn = np.array(state[5], dtype=np.float64)   # linkWorldOrientation
        return pos, orn

    # ------------------------------------------------------------------- IK

    def solve_ik(
        self,
        target_pos: Sequence[float],
        target_orn: Sequence[float] | None = None,
        max_iterations: int = 50,
        residual_threshold: float = 1e-4,
    ) -> np.ndarray:
        """Damped-least-squares IK for the tool link.

        Args:
            target_pos: (x, y, z) in world frame.
            target_orn: (qx, qy, qz, qw) in world frame, or None for
                position-only IK (solver picks orientation freely).
            max_iterations, residual_threshold: passed to PyBullet.

        Returns:
            Array of 6 target joint angles, already clipped to limits.

        Notes:
            PyBullet's IK returns one value per joint in the body,
            including fixed joints. We slice out the 6 revolute ones.

            We feed joint limits + a rest pose to the solver. Without
            this, damped LS on a 6-DOF arm produces contorted solutions
            (elbow flipped, wrist wrapped). With it, solutions stay
            near the home pose, which is what a control loop expects.
        """
        target_pos = list(target_pos)

        # Rest pose = current target. Keeps successive IK calls smooth
        # (each solve starts near the last commanded pose).
        rest_pose = self._target_q.tolist()

        # joint_ranges is upper - lower per joint; standard PyBullet idiom.
        lowers = self.joint_limits_lower.tolist()
        uppers = self.joint_limits_upper.tolist()
        ranges = (self.joint_limits_upper - self.joint_limits_lower).tolist()

        common_kwargs = dict(
            bodyUniqueId=self.body_id,
            endEffectorLinkIndex=self.ee_link_index,
            targetPosition=target_pos,
            lowerLimits=lowers,
            upperLimits=uppers,
            jointRanges=ranges,
            restPoses=rest_pose,
            maxNumIterations=max_iterations,
            residualThreshold=residual_threshold,
            physicsClientId=self.world.client_id,
        )
        if target_orn is not None:
            common_kwargs["targetOrientation"] = list(target_orn)

        raw = p.calculateInverseKinematics(**common_kwargs)

        # `raw` has one entry per joint in the body. Our 6 revolute
        # joints appear in the order we discovered them; PyBullet's IK
        # returns them in the same order (joints are enumerated by
        # index, and non-fixed joints appear in that order in the IK
        # output). Extract the first 6 — for xArm 6 the body has
        # exactly 6 non-fixed joints, so raw is already length 6.
        q = np.asarray(raw, dtype=np.float64)
        if q.shape != (XARM6_NUM_JOINTS,):
            # Defensive fallback: if the URDF ever gains extra movable
            # joints (e.g. a gripper), take just the arm joints by
            # position among non-fixed joints. For now this branch is
            # unreachable with the bundled URDF.
            q = q[:XARM6_NUM_JOINTS]

        return np.clip(q, self.joint_limits_lower, self.joint_limits_upper)
