"""xArm 6 wrapper: load, home pose, joint state, position control.

Uses the flat xArm 6 URDF that ships with `pybullet_data` — no vendoring,
no extra deps. This is the UFactory model, autogenerated from their
official xacro (see bulletphysics/bullet3, path: pybullet_data/xarm/).

Scope of this commit: get the arm on screen, holding a home pose, and
respond to `set_joint_positions()`. No IK yet — that's the next commit,
where a debug marker feeds a target pose to a `solve_ik()` method here.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Sequence

import numpy as np
import pybullet as p
import pybullet_data

from sim.world import World

# ---------------------------------------------------------------- constants

# xArm 6 has 6 revolute joints. The bundled URDF's link6 is the last
# link and doubles as the tool frame (there is no separate `link_eef`).
XARM6_URDF_RELPATH = "xarm/xarm6_robot.urdf"
XARM6_NUM_JOINTS = 6

# Battle-tested "ready to reach forward" home pose for xArm 6 in PyBullet:
# base facing +x, shoulder tilted, elbow bent, wrist pointed down-ish.
# Values borrowed from the Google Research xarm_sim_robot reference
# (deg2rad([0, -20, -80, 0, 100, -30])).
DEFAULT_HOME_POSE_RAD: tuple[float, ...] = (
    0.0, -0.349, -1.396, 0.0, 1.745, -0.524,
)


# ------------------------------------------------------------------ config

@dataclass
class ArmConfig:
    """All tunable knobs for the arm. Base pose is separate because the
    AGV mount (commit 6) will override it at construction time."""

    base_position: tuple[float, float, float] = (0.0, 0.0, 0.0)
    base_orientation_rpy: tuple[float, float, float] = (0.0, 0.0, 0.0)

    home_pose_rad: tuple[float, ...] = DEFAULT_HOME_POSE_RAD

    # POSITION_CONTROL parameters. Defaults match what pybullet's
    # own examples use for the xArm; tune per-joint later if needed.
    max_force: float = 100.0
    position_gain: float = 0.03
    velocity_gain: float = 1.0

    # If True, use resetJointState (teleport) on reset() to snap to home
    # before the sim starts stepping. If False, home is reached under
    # position control after step-in.
    snap_to_home: bool = True

    def __post_init__(self) -> None:
        if len(self.home_pose_rad) != XARM6_NUM_JOINTS:
            raise ValueError(
                f"home_pose_rad must have {XARM6_NUM_JOINTS} entries, "
                f"got {len(self.home_pose_rad)}"
            )


# --------------------------------------------------------------------- arm

class Arm:
    """PyBullet xArm 6 wrapper attached to a World.

    Owns:
        - the loaded URDF body id
        - the mapping from arm joints to PyBullet joint indices
        - the current target joint positions (applied every control tick)

    Does not own:
        - the physics loop (that's World)
        - IK solving (that's the next commit)
        - the base pose after construction (the AGV mount will move it)
    """

    def __init__(self, world: World, cfg: ArmConfig | None = None) -> None:
        self.world = world
        self.cfg = cfg or ArmConfig()

        self.body_id: int = -1
        self.joint_indices: list[int] = []  # PyBullet joint indices for the 6 revolute joints
        self.joint_names: list[str] = []
        self.joint_limits_lower: np.ndarray = np.zeros(XARM6_NUM_JOINTS)
        self.joint_limits_upper: np.ndarray = np.zeros(XARM6_NUM_JOINTS)
        self.ee_link_index: int = -1  # link6 — tool frame

        # Current position-control target. Updated by set_joint_positions()
        # and re-applied every control_step().
        self._target_q: np.ndarray = np.array(self.cfg.home_pose_rad,
                                              dtype=np.float64)

    # ------------------------------------------------------------- lifecycle

    def reset(self) -> None:
        """Load the URDF, discover joint indices, and go to home pose."""
        if self.world.client_id < 0:
            raise RuntimeError("World.reset() must be called before Arm.reset()")

        urdf_path = os.path.join(pybullet_data.getDataPath(),
                                 XARM6_URDF_RELPATH)
        if not os.path.isfile(urdf_path):
            raise FileNotFoundError(
                f"xArm 6 URDF not found at {urdf_path}. "
                "Is pybullet_data installed? (pip install pybullet)"
            )

        base_orn = p.getQuaternionFromEuler(self.cfg.base_orientation_rpy)
        self.body_id = p.loadURDF(
            urdf_path,
            basePosition=self.cfg.base_position,
            baseOrientation=base_orn,
            useFixedBase=True,
            physicsClientId=self.world.client_id,
        )

        self._discover_joints()

        # Reset current target to home before we snap or command.
        self._target_q = np.array(self.cfg.home_pose_rad, dtype=np.float64)

        if self.cfg.snap_to_home:
            for idx, q in zip(self.joint_indices, self._target_q):
                p.resetJointState(self.body_id, idx, q,
                                  physicsClientId=self.world.client_id)

        # Whether we snapped or not, register the control target so
        # POSITION_CONTROL holds the pose against gravity.
        self._apply_target()

    def _discover_joints(self) -> None:
        """Walk the loaded body's joints and record the 6 revolute ones.

        We don't hardcode joint indices because the URDF has a fixed
        world_joint at index 0 (see the bundled URDF header) — the
        actual revolute joints are indices 1..6. But rather than assume
        that, we scan and take all JOINT_REVOLUTE joints in URDF order.
        """
        n = p.getNumJoints(self.body_id, physicsClientId=self.world.client_id)

        self.joint_indices = []
        self.joint_names = []
        lowers: list[float] = []
        uppers: list[float] = []

        for i in range(n):
            info = p.getJointInfo(self.body_id, i,
                                  physicsClientId=self.world.client_id)
            joint_type = info[2]
            if joint_type != p.JOINT_REVOLUTE:
                continue
            self.joint_indices.append(i)
            self.joint_names.append(info[1].decode("utf-8"))
            lowers.append(info[8])   # jointLowerLimit
            uppers.append(info[9])   # jointUpperLimit

        if len(self.joint_indices) != XARM6_NUM_JOINTS:
            raise RuntimeError(
                f"Expected {XARM6_NUM_JOINTS} revolute joints on the "
                f"xArm 6, found {len(self.joint_indices)}: {self.joint_names}"
            )

        self.joint_limits_lower = np.array(lowers, dtype=np.float64)
        self.joint_limits_upper = np.array(uppers, dtype=np.float64)

        # Tool frame = last link = link6. Its index equals the index of
        # joint6 in the URDF (PyBullet numbers links by their parent joint).
        self.ee_link_index = self.joint_indices[-1]

    # --------------------------------------------------------------- control

    def set_joint_positions(self, q: Sequence[float]) -> None:
        """Set the position-control target. Takes effect on the next
        control_step(). Values are clipped to joint limits."""
        q_arr = np.asarray(q, dtype=np.float64)
        if q_arr.shape != (XARM6_NUM_JOINTS,):
            raise ValueError(
                f"q must have {XARM6_NUM_JOINTS} entries, got shape {q_arr.shape}"
            )
        self._target_q = np.clip(q_arr,
                                 self.joint_limits_lower,
                                 self.joint_limits_upper)
        # Push to the controller immediately so callers who don't drive
        # a control loop still see motion.
        self._apply_target()

    def go_home(self) -> None:
        """Command the home pose as the current target."""
        self.set_joint_positions(self.cfg.home_pose_rad)

    def control_step(self, sim_time_s: float) -> None:
        """Callback for World.register_callback(). Re-applies the current
        joint target every tick. Explicit re-application is cheap and
        protects against the target being cleared by resets or external
        code."""
        self._apply_target()

    def _apply_target(self) -> None:
        p.setJointMotorControlArray(
            bodyUniqueId=self.body_id,
            jointIndices=self.joint_indices,
            controlMode=p.POSITION_CONTROL,
            targetPositions=self._target_q.tolist(),
            forces=[self.cfg.max_force] * XARM6_NUM_JOINTS,
            positionGains=[self.cfg.position_gain] * XARM6_NUM_JOINTS,
            velocityGains=[self.cfg.velocity_gain] * XARM6_NUM_JOINTS,
            physicsClientId=self.world.client_id,
        )

    # ---------------------------------------------------------- introspection

    def get_joint_positions(self) -> np.ndarray:
        """Actual current joint angles (not the target)."""
        states = p.getJointStates(self.body_id, self.joint_indices,
                                  physicsClientId=self.world.client_id)
        return np.array([s[0] for s in states], dtype=np.float64)

    def get_target_positions(self) -> np.ndarray:
        return self._target_q.copy()

    def get_ee_pose(self) -> tuple[np.ndarray, np.ndarray]:
        """World-frame (position, quaternion) of the tool link."""
        state = p.getLinkState(self.body_id, self.ee_link_index,
                               computeForwardKinematics=True,
                               physicsClientId=self.world.client_id)
        pos = np.array(state[4], dtype=np.float64)   # linkWorldPosition
        orn = np.array(state[5], dtype=np.float64)   # linkWorldOrientation
        return pos, orn
